language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="https://www.djangoproject.com/download/1.6a1/tarball/"
  - DJANGO="django==1.5.1 --use-mirrors"
  - DJANGO="django==1.4.5 --use-mirrors"
  - DJANGO="django==1.3.7 --use-mirrors"

install:
  - pip install $DJANGO
  - python setup.py develop


script:
  - python ./demo/manage.py test polls
