language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
  - DJANGO="django==1.6.2 --use-mirrors"
  - DJANGO="django==1.5.5 --use-mirrors"
  - DJANGO="django==1.4.10 --use-mirrors"
  - DJANGO="django==1.3.7 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install pytest pytest-django
  - python setup.py develop


script:
  - py.test demo/polls

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO="django==1.4.10 --use-mirrors"
    - python: "3.2"
      env: DJANGO="django==1.3.7 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.4.10 --use-mirrors"
    - python: "3.3"
      env: DJANGO="django==1.3.7 --use-mirrors"
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
